This was generated by doing pip freeze after being able to run a test successfully.

I installed the following in a virtual env:
pip install mock
pip install pytest
pip install hacking
env LDFLAGS="-L$(brew --prefix openssl)/lib" CFLAGS="-I$(brew --prefix openssl)/include" pip install cryptography
pip install f5-openstack-agent
pip install oslo.log
pip install eventlet


Babel (2.3.4)
cffi (1.9.1)
cryptography (1.5.3)
debtcollector (1.9.0)
enum34 (1.1.6)
eventlet (0.19.0)
f5-icontrol-rest (1.0.9)
f5-openstack-agent (8.1.0)
f5-sdk (1.5.0)
flake8 (2.5.5)
funcsigs (1.0.2)
greenlet (0.4.10)
hacking (0.12.0)
idna (2.1)
ipaddress (1.0.17)
iso8601 (0.1.11)
mccabe (0.2.1)
mock (2.0.0)
monotonic (1.2)
msgpack-python (0.4.8)
netaddr (0.7.18)
netifaces (0.10.5)
oslo.config (3.19.0)
oslo.context (2.10.0)
oslo.i18n (3.10.0)
oslo.log (3.17.0)
oslo.serialization (2.14.0)
oslo.utils (3.18.0)
pbr (1.10.0)
pep8 (1.5.7)
pip (7.1.2)
positional (1.1.1)
py (1.4.31)
pyasn1 (0.1.9)
pycparser (2.17)
pyflakes (0.8.1)
pyparsing (2.1.10)
pytest (3.0.4)
python-dateutil (2.6.0)
pytz (2016.7)
requests (2.12.1)
rfc3986 (0.4.1)
setuptools (18.2)
six (1.10.0)
stevedore (1.18.0)
wheel (0.24.0)
wrapt (1.10.8)
